kotlin.code.style=official
kotlinVersion=2.1.0
kotlinxIoVersion=0.6.0
coroutinesVersion=1.10.1
scramClientVersion=2.1
serializationJsonVersion=1.7.3
kotlinxSerializationPluginVersion=2.1.0
kotlinx.atomicfu.enableJvmIrTransformation=true
kotlinxAtomicFuVersion=0.26.1
junitVersion=5.11.4
kotlinLoggingVersion=7.0.3
logbackVersion=1.5.13
slf4jVersion=2.0.16
mockkVersion=1.13.13
ktorVersion=3.0.3
mavenPublishVersion=0.28.0
dokkaVersion=2.0.0
org.jetbrains.dokka.experimental.gradle.pluginMode=V2EnabledWithHelpers
kotlinCsvVersion=1.10.0
ktfmtVersion=0.21.0
