#!/bin/bash
podman pull docker.io/postgis/postgis

dir="/home/$USER/kdbc-test-dbs"
mkdir -p "$dir/postgresql"

postgresPassword="${POSTGRES_PASSWORD}"
if [[ -z "${postgresPassword}" ]]; then
  read -s -p "Postgres Password: " postgresPassword
  echo ""
  if [[ -z "${postgresPassword}" ]]; then
      echo "No value provided for postgres password"
      exit 1
  fi
fi

podman pod create --name kdbc-test-dbs -p 5432:5432
podman create --pod=kdbc-test-dbs \
    --name kdbc-test-pg \
    -e "POSTGRES_PASSWORD=${postgresPassword}" \
    -v "$dir/postgresql:/var/lib/postgresql/data:Z" \
    postgis/postgis
